name: SecureSDLC

on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main
      - master

jobs:
  fetch-securesdlc:
    runs-on: ubuntu-24.04
    steps:
      - name: Fetch workflow file
        run: |
          curl -s -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.SDLC_READ_ACTION }}" \
            -o downstream-workflow.json \
            "https://api.github.com/repos/dso-migrateme/securesdlc-sast/contents/.github/workflows/securesdlc-sast.yml"
      - name: Decode workflow
        run: |
          ls
          cat downstream-workflow.json | jq -r .content | base64 -d > workflow.yml
          cat workflow.yml

  run-securesdlc:
    runs-on: ubuntu-24.04
    needs: fetch-securesdlc
    steps:
     - name: Run workflow
       uses: workflow.yml

  # include-securesdlc:
  #   needs: authenticate
  #   uses: dso-migrateme/securesdlc-sast/.github/workflows/securesdlc-sast.yml@main
