name: SecureSDLC

on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main
      - master

jobs:
  pull-and-run-securesdlc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Public Repository
        uses: actions/checkout@v3

      - name: Authenticate with Repo Token
        run: echo "${{ secrets.SDLC_READ_ACTION }}" | gh auth login --with-token

      - name: Fetch Workflow from Private Repo
        env:
          PAT: ${{ secrets.SDLC_READ_ACTION }}
        run: |
          curl -s -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${PAT}" \
            "https://api.github.com/repos/dso-migrateme/securesdlc-sast/contents/.github/workflows/securesdlc-sast.yml" \
            jq -r .content | base64 > .github/workflows/reusable-workflow.yml
          cat .github/workflows/reusable-workflow.yml

      # - name: Run the Fetched Workflow
      #   run: |
      #     echo "Running the fetched workflow dynamically..."
      #     cat .github/workflows/reusable-workflow.yml
      #     # Add logic here to execute the fetched workflow if needed

    # run-securesdlc:
    #   runs-on: ubuntu-latest
    #   uses: .github/workflows/reusable-workflow.yml

  # include-securesdlc:
  #   needs: authenticate
  #   uses: dso-migrateme/securesdlc-sast/.github/workflows/securesdlc-sast.yml@main
