name: SecureSDLC

on:
  workflow_dispatch: {}
  pull_request: {}
  workflow_call: {} # needed when being called from other workflow
  push:
    branches:
      - main
      - master

jobs:
  securesdlc:
    runs-on: ubuntu-24.04
    steps:
      - name: Test
        run: |
          echo "hi"

  #   uses: dso-migrateme/securesdlc-sast/.github/workflows/securesdlc-sast.yml@main

