name: SecureSDLC Umbrella

on:
  workflow_dispatch: {}
  pull_request: {}
  workflow_call: {}

jobs:
  securesdlc-test:
    runs-on: ubuntu-24.04
    steps:
      - name: securesdlc-test
        run: |
          echo "securesdlc-test"

  securesdlc-umbrella:
    uses: dso-migrateme/securesdlc-sast/.github/workflows/securesdlc-sast.yml@main

