name: SecureSDLC Umbrella

on:
  workflow_dispatch: {}
  pull_request: {}
  workflow_call: {}

jobs:
  securesdlc-umbrella:
    runs-on: ubuntu-24.04
    steps:
      - name: securesdlc-umbrella
        run: |
          echo "hi"

  #   uses: dso-migrateme/securesdlc-sast/.github/workflows/securesdlc-sast.yml@main

