name: SecureSDLC


jobs:
  securesdlc:
    runs-on: ubuntu-24.04
    steps:
      - name: test
        run: |
          echo "hi"

  #   uses: dso-migrateme/securesdlc-sast/.github/workflows/securesdlc-sast.yml@main

