name: SecureSDLC Umbrella
run-name: "[Required SecureSDLC Workflow] Ref:${{ github.ref_name }}"

on:
  workflow_dispatch: {}
  workflow_call: {}
  pull_request: {}
  # pull_request_target: {} # Gives workflows excessive permissions. Not wanted.

jobs:
  securesdlc-check:
    runs-on: ubuntu-24.04
    steps:
      - name: securesdlc-check
        run: |
          echo "securesdlc-test"
          echo ${{ github.ref_name }}
          echo ${{ github.event.repository.default_branch }}
          echo "TEST_SECRET: ${{ secrets.TEST_SECRET }}"

  securesdlc-umbrella:
    uses: dso-migrateme/securesdlc-sast/.github/workflows/securesdlc-sast.yml@main
    secrets:
      # SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
      PASSED: ${{ secrets.TEST_SECRET }}

