name: SecureSDLC

on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main
      - master

jobs:
  pull-securesdlc:
    runs-on: ubuntu-24.04
    steps:
      - name: Fetch workflow
        env:
          PAT: ${{ secrets.SDLC_READ_ACTION }}
        run: |
          curl -s -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${PAT}" \
            "https://api.github.com/repos/dso-migrateme/securesdlc-sast/contents/.github/workflows/securesdlc-sast.yml" \
            jq -r .content
        run: |
          ls
          cat downstream-workflow.yml
          # cat downstream-workflow.yml | base64 -d
      # - name: Run downstream workflow
      #   run: echo "${{ secrets.SDLC_READ_ACTION }}" | gh auth login --with-token



  # run-securesdlc:
  #   runs-on: ubuntu-24.04
  #   uses: .github/workflows/reusable-workflow.yml

  # include-securesdlc:
  #   needs: authenticate
  #   uses: dso-migrateme/securesdlc-sast/.github/workflows/securesdlc-sast.yml@main
