name: SecureSDLC

on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main
      - master

jobs:
  fetch-securesdlc:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Fetch workflow file
        run: |
          curl -s -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.SDLC_READ_ACTION }}" \
            -o downstream-workflow-file.json \
            "https://api.github.com/repos/dso-migrateme/securesdlc-sast/contents/.github/workflows/securesdlc-sast.yml"
      - name: Decode workflow
        run: |
          cat downstream-workflow-file.json | jq -r .content | base64 -d > .github/workflows/workflow.yml
          # cat .github/workflows/workflow.yml

  run-securesdlc:
    runs-on: ubuntu-24.04
    needs: fetch-securesdlc
    name: aaa
    uses: .github/workflows/workflow.yml

  # include-securesdlc:
  #   needs: authenticate
  #   uses: dso-migrateme/securesdlc-sast/.github/workflows/securesdlc-sast.yml@main
