name: SecureSDLC
run-name: "[Required SecureSDLC Workflow] Ref:${{ github.ref_name }}"

on:
  workflow_dispatch: {}
  workflow_call: {}
  pull_request: {}
  # pull_request_target: {} # Gives workflows excessive permissions. Not wanted.

jobs:
  securesdlc:
    uses: nautilus-wraith/securesdlc-umbrella/.github/workflows/securesdlc.yml@main
    # secrets:
    #   SEMGREP_APP_URL: ${{ secrets.SEMGREP_APP_URL }}
    #   SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

