name: SecureSDLC Umbrella

on:
  workflow_dispatch: {}
  workflow_call: {}
  pull_request: {}
  # pull_request_target: {} # Gives workflows higher permissions. Not desired when working with public forks.


jobs:
  securesdlc-test:
    runs-on: ubuntu-24.04
    steps:
      - name: securesdlc-test
        run: |
          echo "securesdlc-test"

  securesdlc-umbrella:
    uses: dso-migrateme/securesdlc-sast/.github/workflows/securesdlc-sast.yml@main

