name: SecureSDLC

on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main
      - master

jobs:
  authenticate:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate with GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
  include-securesdlc:
    needs: authenticate
    uses: dso-migrateme/securesdlc-sast/.github/workflows/securesdlc-sast.yml@main
