name: SecureSDLC Umbrella
run-name: "[Required SecureSDLC Workflow] Ref:${{ github.ref_name }}"

on:
  workflow_dispatch: {}
  workflow_call: {}
  pull_request: {}
  # pull_request_target: {} # Gives workflows excessive permissions. Not wanted.

jobs:
  securesdlc-check:
    runs-on: ubuntu-24.04
    steps:
      - name: securesdlc-check
        run: |
          echo "securesdlc-test"
          echo ${{ github.ref_name }}

  securesdlc-umbrella:
    uses: dso-migrateme/securesdlc-sast/.github/workflows/securesdlc-sast.yml@main

